-- SEED DATA

INSERT INTO regiones (nombre) VALUES ('Norte'), ('Centro'), ('Sur') ON CONFLICT (nombre) DO NOTHING;
DO $$
DECLARE north_id UUID; BEGIN SELECT id INTO north_id FROM regiones WHERE nombre = 'Norte';
-- Empresas
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '08907f5d', '08907f5d', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '0ee9e444', '0ee9e444', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '10521524', '10521524', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '13d98fe5', '13d98fe5', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '147c24d1', '147c24d1', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '15add3cc', '15add3cc', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '1bfdac78', '1bfdac78', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '1c018b46', '1c018b46', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '22c1f3b4', '22c1f3b4', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '26ff4dce', '26ff4dce', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '27064207', '27064207', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '28fe4aa4', '28fe4aa4', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '2d93f20a', '2d93f20a', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '2dc3af61', '2dc3af61', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '38e2d7de', '38e2d7de', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '3af844cd', '3af844cd', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '47c7929c', '47c7929c', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '49697ee0', '49697ee0', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '4bf2a2fc', '4bf2a2fc', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '4e1660be', '4e1660be', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '5250d65f', '5250d65f', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '61fc618a', '61fc618a', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '667f56b5', '667f56b5', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '6ea97e20', '6ea97e20', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '6f964b19', '6f964b19', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '77e0339d', '77e0339d', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '84d49fff', '84d49fff', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '85b1f35d', '85b1f35d', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '889b779b', '889b779b', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '8f8c12da', '8f8c12da', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '8fc7f90f', '8fc7f90f', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '934264b8', '934264b8', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '99f01d97', '99f01d97', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT '9a2e27cc', '9a2e27cc', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'a3c0f724', 'a3c0f724', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'a519da7c', 'a519da7c', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'a73668ff', 'a73668ff', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'a81670d9', 'a81670d9', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'ab7bb2e4', 'ab7bb2e4', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'b08eb990', 'b08eb990', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'bf552330', 'bf552330', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'c1bc0625', 'c1bc0625', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'cb096e8b', 'cb096e8b', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'cb6800ba', 'cb6800ba', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'cec3350c', 'cec3350c', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'd0fcfb46', 'd0fcfb46', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'd6a3ec9a', 'd6a3ec9a', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'ddf9b0a1', 'ddf9b0a1', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'e5c208b9', 'e5c208b9', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'e607a7e0', 'e607a7e0', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'ec3dbb5d', 'ec3dbb5d', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d102', 'f0fb2d102', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d103', 'f0fb2d103', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d104', 'f0fb2d104', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d105', 'f0fb2d105', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d108', 'f0fb2d108', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d110', 'f0fb2d110', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d114', 'f0fb2d114', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d117', 'f0fb2d117', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d119', 'f0fb2d119', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d120', 'f0fb2d120', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d123', 'f0fb2d123', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d125', 'f0fb2d125', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d133', 'f0fb2d133', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d138', 'f0fb2d138', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d145', 'f0fb2d145', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d146', 'f0fb2d146', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d147', 'f0fb2d147', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d148', 'f0fb2d148', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d149', 'f0fb2d149', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d21', 'f0fb2d21', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d26', 'f0fb2d26', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d33', 'f0fb2d33', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d34', 'f0fb2d34', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d46', 'f0fb2d46', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d49', 'f0fb2d49', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d50', 'f0fb2d50', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d54', 'f0fb2d54', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d56', 'f0fb2d56', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d58', 'f0fb2d58', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d59', 'f0fb2d59', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d63', 'f0fb2d63', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d71', 'f0fb2d71', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d73', 'f0fb2d73', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d80', 'f0fb2d80', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d81', 'f0fb2d81', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d83', 'f0fb2d83', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d89', 'f0fb2d89', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d90', 'f0fb2d90', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d95', 'f0fb2d95', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f0fb2d98', 'f0fb2d98', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f161709d', 'f161709d', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'f8eb2957', 'f8eb2957', north_id ON CONFLICT (codigo_cliente) DO NOTHING;
INSERT INTO empresas (nombre, codigo_cliente, region_id) SELECT 'fd3a97b6', 'fd3a97b6', north_id ON CONFLICT (codigo_cliente) DO NOTHING;

-- Tipos de Muestrario
INSERT INTO muestrarios_tipos (nombre, sla_dias_estandar) VALUES ('Contrapeso Diamond', 5) ON CONFLICT DO NOTHING;
INSERT INTO muestrarios_tipos (nombre, sla_dias_estandar) VALUES ('Laminas Sunset R', 5) ON CONFLICT DO NOTHING;
INSERT INTO muestrarios_tipos (nombre, sla_dias_estandar) VALUES ('Laminas Waves', 5) ON CONFLICT DO NOTHING;
INSERT INTO muestrarios_tipos (nombre, sla_dias_estandar) VALUES ('Muestrarios', 5) ON CONFLICT DO NOTHING;
END $$;
